"""add node.key (logical id)

Revision ID: 64f7dcc41f91
Revises: 91570da90011
Create Date: 2025-08-17 13:00:08.076391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64f7dcc41f91'
down_revision: Union[str, Sequence[str], None] = '91570da90011'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('nodes', sa.Column('key', sa.String(), nullable=True))
    op.create_index(op.f('ix_nodes_key'), 'nodes', ['key'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nodes_key'), table_name='nodes')
    op.drop_column('nodes', 'key')
    # ### end Alembic commands ###
