name: CI

on:
  push:
  pull_request:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11']
        node-version: ['18', '20']
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: dashboard/mini/package-lock.json

      - name: Install backend dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
          pip install ruff pytest-cov

      - name: Lint backend
        run: ruff check .

      - name: Test backend
        run: pytest --cov=. --cov-report=xml --cov-report=html --cov-fail-under=85

      - name: Install frontend dependencies
        working-directory: dashboard/mini
        run: npm ci

      - name: Lint frontend
        working-directory: dashboard/mini
        run: npm run lint

      - name: Typecheck frontend
        working-directory: dashboard/mini
        run: npm run typecheck

      - name: Test frontend
        working-directory: dashboard/mini
        run: npm test -- --run --coverage

      - name: Upload coverage artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.python-version }}-node${{ matrix.node-version }}
          path: |
            coverage.xml
            htmlcov
            dashboard/mini/coverage

  alembic-heads:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .

      - name: Check Alembic heads
        run: |
          alembic heads
          test $(alembic heads | wc -l) -eq 1

  coverage-merge:
    needs: lint-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: coverage-*
          path: coverage
          merge-multiple: true

      - name: Upload combined coverage
        uses: codecov/codecov-action@v4
        with:
          files: "coverage/**/coverage.xml,coverage/**/lcov.info"
          fail_ci_if_error: false

  deploy-pages:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: lint-and-test
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: dashboard/mini/package-lock.json

      - name: Install dependencies
        working-directory: dashboard/mini
        run: npm ci

      - name: Build
        working-directory: dashboard/mini
        run: npm run build

      - name: Configure Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dashboard/mini/dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  vercel-deploy:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: lint-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: dashboard/mini/package-lock.json

      - name: Install dependencies
        working-directory: dashboard/mini
        run: npm ci

      - name: Build
        working-directory: dashboard/mini
        run: npm run build

      - name: Deploy to Vercel
        id: deploy
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: dashboard/mini
          vercel-args: '--prebuilt --prod'

      - name: "Afficher l'URL publique"
        run: |
          echo "URL de déploiement: ${{ steps.deploy.outputs.preview-url }}"
