name: CI

on:
  push:
  pull_request:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11']
        node-version: ['18', '20']
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: dashboard/mini/package-lock.json

      - name: Install backend dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
          pip install ruff pytest-cov

      - name: Lint backend
        run: ruff check .

      - name: Test backend
        run: pytest --cov=. --cov-report=xml --cov-report=html --cov-fail-under=85

      - name: Install frontend dependencies
        working-directory: dashboard/mini
        run: npm ci

      - name: Lint frontend
        working-directory: dashboard/mini
        run: npm run lint

      - name: Typecheck frontend
        working-directory: dashboard/mini
        run: npm run typecheck

      - name: Test frontend
        working-directory: dashboard/mini
        run: npm test -- --coverage

      - name: Upload coverage artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.python-version }}-node${{ matrix.node-version }}
          path: |
            coverage.xml
            htmlcov
            dashboard/mini/coverage

  alembic-heads:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
      - name: Check Alembic heads
        run: |
          alembic heads
          test $(alembic heads | wc -l) -eq 1

  coverage-merge:
    needs: lint-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: coverage-*
          path: coverage
          merge-multiple: true
      - name: Upload combined coverage
        uses: codecov/codecov-action@v4
        with:
          files: "coverage/**/coverage.xml,coverage/**/lcov.info"
          fail_ci_if_error: false

  vercel-deploy:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: lint-and-test
    runs-on: ubuntu-latest
    outputs:
      preview-url: ${{ steps.deploy.outputs.preview-url }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: dashboard/mini/package-lock.json
      - name: Install dependencies
        working-directory: dashboard/mini
        run: npm ci
      - name: Build
        working-directory: dashboard/mini
        run: npm run build
      - name: Deploy to Vercel
        id: deploy
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: dashboard/mini
          vercel-args: '--prebuilt --prod'
      - name: Afficher l’URL publique
        run: |
          echo "URL de déploiement: ${{ steps.deploy.outputs.preview-url }}"

  e2e-preview:
    needs:
      - lint-and-test
      - vercel-deploy
    if: ${{ needs.vercel-deploy.result == 'success' || github.ref != 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: dashboard/mini/package-lock.json
      - name: Install dependencies
        working-directory: dashboard/mini
        run: npm ci
      - name: Cache Playwright
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ hashFiles('dashboard/mini/package-lock.json') }}
      - name: Install Playwright
        working-directory: dashboard/mini
        run: npx playwright install --with-deps
      - name: Run E2E tests (preview)
        working-directory: dashboard/mini
        env:
          PREVIEW_URL: ${{ needs.vercel-deploy.outputs.preview-url || secrets.PREVIEW_URL }}
        run: npm run e2e:ci
      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: dashboard/mini/playwright-report
