name: Cockpit CI

on:
  push:
    paths:
      - 'frontend/cockpit/**'
      - '.github/workflows/cockpit-ci.yml'
  pull_request:
    paths:
      - 'frontend/cockpit/**'
      - '.github/workflows/cockpit-ci.yml'

jobs:
  install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20, 22]
    defaults:
      run:
        working-directory: frontend/cockpit
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm
          cache-dependency-path: frontend/cockpit/package-lock.json
      - run: npm ci

  lint:
    runs-on: ubuntu-latest
    needs: install
    strategy:
      matrix:
        node: [20, 22]
    defaults:
      run:
        working-directory: frontend/cockpit
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm
          cache-dependency-path: frontend/cockpit/package-lock.json
      - run: npm ci
      - run: npm run lint
      - if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: eslint-report-${{ matrix.node }}
          path: frontend/cockpit/reports/lint

  unit:
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        node: [20, 22]
    defaults:
      run:
        working-directory: frontend/cockpit
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm
          cache-dependency-path: frontend/cockpit/package-lock.json
      - run: npm ci
      - run: npm test
      - if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: jest-report-${{ matrix.node }}
          path: frontend/cockpit/reports/jest

  build:
    runs-on: ubuntu-latest
    needs: unit
    strategy:
      matrix:
        node: [20, 22]
    defaults:
      run:
        working-directory: frontend/cockpit
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm
          cache-dependency-path: frontend/cockpit/package-lock.json
      - run: npm ci
      - run: npm run build

  audit:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        node: [20]
    defaults:
      run:
        working-directory: frontend/cockpit
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm
          cache-dependency-path: frontend/cockpit/package-lock.json
      - run: npm ci
      - run: npm run build
      - name: Install Lighthouse
        run: npm i -g lighthouse chrome-launcher
      - name: Start server
        run: npm start &
      - name: Run Lighthouse CI (≥ 90)
        env:
          URL: http://localhost:3000
          LH_MIN: '0.9'
          LIGHTHOUSE_BIN: lighthouse
        run: node scripts/lh-ci.mjs
      - name: Upload Lighthouse report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cockpit-lighthouse-report
          path: |
            frontend/cockpit/lighthouse-report.json
            frontend/cockpit/lh-summary.md
