name: Deploy Preview

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - preview

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: preview-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      preview-url: ${{ steps.vercel-deploy.outputs.url }}
    steps:
      - uses: actions/checkout@v4

      - name: Pull Vercel Environment Information
        uses: vercel/actions/pull@v1
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: dashboard/mini

      - name: Deploy to Vercel
        id: vercel-deploy
        uses: vercel/actions/deploy@v1
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: dashboard/mini

      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const url = process.env.DEPLOY_URL;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Preview Vercel disponible: ${url}`
            });
        env:
          DEPLOY_URL: ${{ steps.vercel-deploy.outputs.url }}
